server:
              port: 8010

              spring:
                thymeleaf:
                  cache: false
                  mode: LEGACYHTML5
                  prefix: classpath:/templates/
                  suffix: .html

